/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as StylistRouteImport } from './routes/stylist'
import { Route as StylerRouteImport } from './routes/styler'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as CouplesRouteImport } from './routes/couples'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTodayRouteImport } from './routes/api/today'
import { Route as ApiTagItemRouteImport } from './routes/api/tag-item'
import { Route as ApiInspirationRouteImport } from './routes/api/inspiration'
import { Route as ApiCollabOutfitsRouteImport } from './routes/api/collab-outfits'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const StylerRoute = StylerRouteImport.update({
  id: '/styler',
  path: '/styler',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const CouplesRoute = CouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodayRoute = ApiTodayRouteImport.update({
  id: '/api/today',
  path: '/api/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagItemRoute = ApiTagItemRouteImport.update({
  id: '/api/tag-item',
  path: '/api/tag-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInspirationRoute = ApiInspirationRouteImport.update({
  id: '/api/inspiration',
  path: '/api/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollabOutfitsRoute = ApiCollabOutfitsRouteImport.update({
  id: '/api/collab-outfits',
  path: '/api/collab-outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/outfits': typeof OutfitsRoute
  '/styler': typeof StylerRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collab-outfits': typeof ApiCollabOutfitsRoute
  '/api/inspiration': typeof ApiInspirationRoute
  '/api/tag-item': typeof ApiTagItemRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/outfits': typeof OutfitsRoute
  '/styler': typeof StylerRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collab-outfits': typeof ApiCollabOutfitsRoute
  '/api/inspiration': typeof ApiInspirationRoute
  '/api/tag-item': typeof ApiTagItemRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/outfits': typeof OutfitsRoute
  '/styler': typeof StylerRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/collab-outfits': typeof ApiCollabOutfitsRoute
  '/api/inspiration': typeof ApiInspirationRoute
  '/api/tag-item': typeof ApiTagItemRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/couples'
    | '/inspiration'
    | '/login'
    | '/outfits'
    | '/styler'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/collab-outfits'
    | '/api/inspiration'
    | '/api/tag-item'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/couples'
    | '/inspiration'
    | '/login'
    | '/outfits'
    | '/styler'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/collab-outfits'
    | '/api/inspiration'
    | '/api/tag-item'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  id:
    | '__root__'
    | '/'
    | '/couples'
    | '/inspiration'
    | '/login'
    | '/outfits'
    | '/styler'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/collab-outfits'
    | '/api/inspiration'
    | '/api/tag-item'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouplesRoute: typeof CouplesRoute
  InspirationRoute: typeof InspirationRoute
  LoginRoute: typeof LoginRoute
  OutfitsRoute: typeof OutfitsRoute
  StylerRoute: typeof StylerRoute
  StylistRoute: typeof StylistRoute
  TodayRoute: typeof TodayRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCollabOutfitsRoute: typeof ApiCollabOutfitsRoute
  ApiInspirationRoute: typeof ApiInspirationRoute
  ApiTagItemRoute: typeof ApiTagItemRoute
  ApiTodayRoute: typeof ApiTodayRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTryonRoute: typeof ApiTryonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styler': {
      id: '/styler'
      path: '/styler'
      fullPath: '/styler'
      preLoaderRoute: typeof StylerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couples': {
      id: '/couples'
      path: '/couples'
      fullPath: '/couples'
      preLoaderRoute: typeof CouplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/today': {
      id: '/api/today'
      path: '/api/today'
      fullPath: '/api/today'
      preLoaderRoute: typeof ApiTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tag-item': {
      id: '/api/tag-item'
      path: '/api/tag-item'
      fullPath: '/api/tag-item'
      preLoaderRoute: typeof ApiTagItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inspiration': {
      id: '/api/inspiration'
      path: '/api/inspiration'
      fullPath: '/api/inspiration'
      preLoaderRoute: typeof ApiInspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collab-outfits': {
      id: '/api/collab-outfits'
      path: '/api/collab-outfits'
      fullPath: '/api/collab-outfits'
      preLoaderRoute: typeof ApiCollabOutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouplesRoute: CouplesRoute,
  InspirationRoute: InspirationRoute,
  LoginRoute: LoginRoute,
  OutfitsRoute: OutfitsRoute,
  StylerRoute: StylerRoute,
  StylistRoute: StylistRoute,
  TodayRoute: TodayRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCollabOutfitsRoute: ApiCollabOutfitsRoute,
  ApiInspirationRoute: ApiInspirationRoute,
  ApiTagItemRoute: ApiTagItemRoute,
  ApiTodayRoute: ApiTodayRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTryonRoute: ApiTryonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
