/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as StylistRouteImport } from './routes/stylist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTodayRouteImport } from './routes/api/today'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodayRoute = ApiTodayRouteImport.update({
  id: '/api/today',
  path: '/api/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stylist': typeof StylistRoute
  '/today': typeof TodayRoute
  '/api/chat': typeof ApiChatRoute
  '/api/today': typeof ApiTodayRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  id:
    | '__root__'
    | '/'
    | '/stylist'
    | '/today'
    | '/api/chat'
    | '/api/today'
    | '/api/transcribe'
    | '/api/tryon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StylistRoute: typeof StylistRoute
  TodayRoute: typeof TodayRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTodayRoute: typeof ApiTodayRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTryonRoute: typeof ApiTryonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/today': {
      id: '/api/today'
      path: '/api/today'
      fullPath: '/api/today'
      preLoaderRoute: typeof ApiTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StylistRoute: StylistRoute,
  TodayRoute: TodayRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTodayRoute: ApiTodayRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTryonRoute: ApiTryonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
